# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fababc7a2f58daa3d2aeabe35bd4a40483eb1836d2a574da0b7ea6baafda8b8ad28fdf4a90959b06a23121b371be2236a50dc6cf0d93f18e09271d87974c3fe

test:
  secret_key_base: bf22639967ad1b6415a630b1de799114838bf17f9e3cb32d1d9737d2c9afe608adb3eb7541be90a01b109537967767ca3c9d2462189d3494772f0b461f42abbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
